### ISSUE TITLE
Terminal height sometimes is used incorrectly

### ISSUE THREAD

**Issue by MHohenberg** [proycon/vocage#1]
I use linux xfce4-terminal under i3wm. Tiling window managers tend to lead to lots on unusual terminal row configurations depending on where and how I set up the window,

When I load a vocab file, the header line is in the top, the footer line is in the bottom. All is well with the world. 

Once I flip a card, though (with Space), the header line disappears - I guess the footer line is one line too low and pushes the header line out of the terminal view window (in fact, when I scroll up, I see it). When switching cards, everything is reset to normal again, until I flip a card.

**Comment by proycon** [comment]
That sounds like a bug indeed, I haven't seen that behaviour myself (dwm+alacritty), but I'll try to reproduce and fix it.

**Comment by MHohenberg** [comment]
I made a video to better show what I am trying to convene: http://martinhohenberg.de/assets/behaviour.mp4

**Comment by proycon** [comment]
Actually, that looks fine :) You can compare it with the animated gif in the README showing the same behaviour. Upon flipping a card, the status message is indeed cleared. It appears again only after executing an action.
