### ISSUE TITLE
Suggestion: Give some information on where vocage saves which pile a card is in

### ISSUE THREAD

**Issue by MHohenberg** [proycon/vocage#2]
I guess the most obvious place to put this is in the main README file. 

**This information is useful for backup purposes.** You wouldn't want to lose your "progress" on huge files when the config gets lost, right?

**Comment by proycon** [comment]
It saves it right inside the tsv file in a new column (i.e. the input file is edited).

(don't forget to press 'w' to save though, if you just press 'q' it quits without saving, perhaps that needs some more finetuning/explanation)

**Comment by MHohenberg** [comment]
Thanks for having a look at this. This is essential information, especially if you want to share vocabulary files. Maybe there is an use case for a cleanup command that removes that information from a file before sharing?

**Comment by proycon** [comment]
I didn't include a cleanup command in vocage itself because it would be fairly trivial to do with existing tools like ``cut``. Perhaps I should document some useful commands you can run in the README.
