### ISSUE TITLE
Comment lines deleted after saving

### ISSUE THREAD

**Issue by gnodar01** [proycon/vocage#3]
Lines beginning with `#` for comments seem to all be stripped after either saving with `w` and/or after clearing the cards for the day.

I'm using iTerm2 + zsh on MacOs.

**Comment by proycon** [comment]
oh! that indeed shouldn't happen. Are the comments in any special part of the file or does it affect all? I think I can see why this happens for leading comments (prior to any non-comments).

**Comment by gnodar01** [comment]
It seems that it indeed happens when there is a comment on the leading non-header line (so the second line in my case). Just to be clear, comments on all lines, as well as empty lines, are removed when there is a comment in the leading line. But when there is no comment in the leading line, all comment lines and empty lines are preserved.

**Comment by proycon** [comment]
This should be solved now in v1.0.1

**Comment by gnodar01** [comment]
Works like a charm. Thank you!
