### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by uunnxx** [proycon/vocage#4]
Can we increase font size in this app without changing font size of terminal?

![vocage](https://user-images.githubusercontent.com/6236057/94759432-8d99fb80-03a8-11eb-8a6e-dbfafa3584c8.png)

**Comment by proycon** [comment]
No, that's one of the inherent limitations of terminal-based applications. The terminal determines the font-size and it is equal for everything that is displayed.

So what I do myself when learning Chinese (I agree the characters are often too small), is simply increase the terminal font size on-the-fly, that works quite well.

**Comment by liabri** [comment]
I understand this is closed but what if to make up for the small font, the text could be converted to an image and put into the terminal via sixel. I believe a good portion of terminals support sixel and it could be optionally enabled via a flag or something. This would sadly make it impossible to copy the text though. 

Not too sure how feasible this is but sounds like a great use for sixel! Maybe the size of the font could be defined in the TSV or with launch commands as some scripts might fit different sizes better.
